version: '3'
services:
  jupyter:
    image: ml-cop:latest
    privileged: true
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/src/notebooks
    environment:
      - DISPLAY=${IP_ADDRESS}:0
    
